---
title: "Dormancia y brotación de semillas en quinua"
description: |
  El viernes 09 de abril de 2021 a horas 16:00, se discutió el artículo de revisión: Seed Dormancy and Preharvest Sprouting in Quinoa.
author:
  - name: Verónica Lecoña
    url: https://franklinsantos.com
    affiliation: Universidad Pública de El Alto
date: 04-30-2021
preview: plant.png
output:
  distill::distill_article:
    self_contained: false
bibliography: refs.bib
---
<style>
body {
text-align: justify}
</style>

### Abstract
Quinoa (*Chenopodium quinoa* Willd.) is a culturally significant staple food source that has been grown for thousands of years in South America. Due to its natural drought and salinity tolerance, quinoa has emerged as an agronomically important crop for production in marginal soils, in highly variable climates, and as part of diverse crop rotations. Primary areas of quinoa research have focused on improving resistance to abiotic stresses and disease, improving yields, and increasing nutrition. However, an evolving issue impacting quinoa seed end-use quality is preharvest sprouting (PHS), which is when seeds with little to no dormancy experience a rain event prior to harvest and sprout on the panicle. Far less is understood about the mechanisms that regulate quinoa seed dormancy and seed viability. This review will cover topics including seed dormancy, orthodox and unorthodox dormancy programs, desiccation sensitivity, environmental and hormonal mechanisms that regulate seed dormancy, and breeding and non-breeding strategies for enhancing resistance to PHS in quinoa.

Cita del artículo @plants

