---
title: "Variación genética de quinua con tolerancia a Peronospora variabilis"
description: |
  El viernes 05 de febrero de 2021 a horas 16:00, se discutió el artículo original: Genetic variation for tolerance to the downy mildew pathogen Peronospora variabilis in genetic resources of quinoa (*Chenopodium quinoa*).
categories:
  - Quinoa
  - Peronospora Variabilitis
  - Genetic Variation
author:
  - name: Verónica Lecoña
    url: https://franklinsantos.com
    affiliation: Universidad Pública de El Alto
date: 02-05-2021
preview: qui.png
output:
  distill::distill_article:
    self_contained: false
bibliography: refs.bib
---

## Abstract
### Background
Quinoa (Chenopodium quinoa Willd.) is an ancient grain crop that is tolerant to abiotic stress and has favorable nutritional properties. Downy mildew is the main disease of quinoa and is caused by infections of the biotrophic oomycete Peronospora variabilis Gaüm. Since the disease causes major yield losses, identifying sources of downy mildew tolerance in genetic resources and understanding its genetic basis are important goals in quinoa breeding.

### Results
We infected 132 South American genotypes, three Danish cultivars and the weedy relative C. album with a single isolate of P. variabilis under greenhouse conditions and observed a large variation in disease traits like severity of infection, which ranged from 5 to 83%. Linear mixed models revealed a significant effect of genotypes on disease traits with high heritabilities (0.72 to 0.81). Factors like altitude at site of origin or seed saponin content did not correlate with mildew tolerance, but stomatal width was weakly correlated with severity of infection. Despite the strong genotypic effects on mildew tolerance, genome-wide association mapping with 88 genotypes failed to identify significant marker-trait associations indicating a polygenic architecture of mildew tolerance.

### Conclusions
The strong genetic effects on mildew tolerance allow to identify genetic resources, which are valuable sources of resistance in future quinoa breeding.

## Journal Club Conclusion
- El artículo presenta resultados sobresalientes que podrían ayudar a identificar genotipos con tolerancia al mildiu.
- La investigación revela que los datos de severidad e incidencia reportados en los registros de pasaporte de las accesiones de los bancos de germoplasma son muy incongruentes con los resultados obtenidos en la investigación. Por tanto, genera incertidumbre de la calidad de información disponible en los bancos de germoplasma.
- La investigación demostró que la infección cruzada de *Chenopodium album* a *Chenopodium quinoa* y viceversa son factibles.


Cita correcta del artículo @Colque







