---
title: "Equipo de investigadores"
description: |
---
## Desarrollador del sitio web
[Franklin Santos](https://franklinsantos.netlify.app)

## Equipo técnico

| Nombres                   | Descripción                   |
|---------------------------|-------------------------------|
| Félix Marza, Ph.D.        | Investigador Principal        |
| Soledad Chavez, B.Sc.     | Investigador Técnico          |
| Franklin Santos, B.Sc.    | Investigador Técnico          |

## Equipo de tesistas
Equipo de investigación durante la campaña agrícola 2019-2020 en la Estación Experimental de Kallutaca de la Universida Pública de El Alto.

| Nombres           | Título de Tésis                   |
|-------------------|-------------------------------|
| Noemy D. Ticona      | Aptitud productiva de nueve líneas élites de trigo harinero (*Triticum aestivum* L.) en el Altiplano norte de La Paz               |
| Alex Mendoza      | Pre-mejoramiento de papa y tubérculos menores en la Estación Experimental de Kallutaca  |
| Cesar R. Pillco     | Rendimiento y valor nutricional de ocho variedades de avena forrajera en condiciones de la Estación Experimental de Kallutaca     |
| Javier Mamani     | Análisis agroeconómico de fuentes orgánicas de fertilización sobre la variedad de papa (*Solanum stenotonum*) Puka Sakampaya en la Estación Experimental de Kallutaca                |
| Verónica Lecona   | Características de productividad, tolerancia a factores bióticos y abióticos adversos en cultivares de quinua preseleccionada bajo condiciones de la Estación Experimental de Kallutaca              |
| Gabriela Aruquipa | Optimización de la aplicación de la fertilización de nitrógeno, fósforo y potasio en los componentes de rendimiento de la cebolla (*Allium cepa* L.) utilizando la metodología de superficie de respuesta (RSM)             |

