---
title: "Ontogénesis y desempeño agronómico de Avena negra"
description: |
  El viernes 19 de febrero de 2021 a horas 16:00, se discutió el artículo original: Black Oat (*Avena strigosa* Schreb.) Ontogenesis and Agronomic Performance in Organic Cropping System and Pannonian Environments.
categories:
  - Oat
  - Black Oats
  - Agro-climatic
author:
  - name: Cesar R. Pillco
    url: https://franklinsantos.com
    affiliation: Universidad Pública de El Alto
date: 02-19-2021
preview: agri.png
output:
  distill::distill_article:
    self_contained: false
bibliography: refs.bib
---
<style>
body {
text-align: justify}
</style>

### Abstract

Este estudio examinó la influencia de las condiciones agroecológicas en la ontogénesis y los rasgos de rendimiento productivo de la avena negra (*Avena strigosa* Schreb.). Comprender las propiedades agronómicas y fenológicas relacionadas con las propiedades productivas de la avena negra puede permitir una introducción más exitosa en nuevas áreas de cultivo de avena. Se realizaron microexperimentos de campo durante los tres años consecutivos (2017-2019) en las dos localidades de South Banat, en Serbia, que diferían en el tipo de suelo: carbonato chernozem y humogley, respectivamente. Los resultados mostraron que todos los rasgos investigados de la avena en el tipo de suelo chernozem fueron más altos en comparación con los rasgos medidos obtenidos del tipo de suelo humogley. El valor promedio de los rendimientos de la biomasa aérea, el rendimiento y el contenido de proteínas fueron significativamente mayores en relación con el humogley, en un 13%, 17% y 11%, respectivamente, para las tres temporadas. Observados por años, todos los parámetros de productividad difirieron significativamente, lo que confirmó que la productividad de las plantas cultivadas estaba fuertemente influenciada por diferentes condiciones agroecológicas, edafoclimáticas en ambientes panónicos. La biomasa aérea y el rendimiento de grano obtenido del tipo de suelo humogley indican que esta especie puede cultivarse con éxito y utilizarse en la producción como cobertura o cultivo forrajero incluso en condiciones de suelo menos favorables.

### Conclusión del Journal Club
- Las condiciones agroedafoclimaticas influen en el comportamiento fenotípico y productividad del cultivo.
- El rendimiento de biomasa aérea, el rendimiento de grano y el contenido de proteína de grano fueron más altos en el tipo de suelo chernozem. 
- Esta especie puede ser cultivado con éxito como cultivo de cobertura o forraje incluso en condiciones de suelo menos favorables.



Cita correcta del artículo @agri









