---
title: "Teledetección e inteligencia artificial en agricultura"
description: |
  El viernes 14 de mayo de 2021 a horas 16:00, se discutió el artículo de revisión: "The potential of remote sensing and artificial intelligence as tools to improve the resilience of agriculture production systems".
categories:
  - Remote Sensing
  - Artificial Intelligence
  - Agriculture
author:
  - name: Gaby Pamela
    url: https://franklinsantos.com
    affiliation: Universidad Pública de El Alto
date: 05-14-2021
preview: img.jpg
output:
  distill::distill_article:
    self_contained: false
bibliography: per.bib
---

<style>
body {
text-align: justify}
</style>

### Abstract
Modern agriculture and food production systems are facing increasing pressures from climate change, land and water availability, and, more recently, a pandemic. These factors are threatening the environmental and economic sustainability of current and future food supply systems. Scientific and technological innovations are needed more than ever to secure enough food for a fast-growing global population. Scientific advances have led to a better understanding of how various components of the agricultural system interact, from the cell to the field level. Despite incredible advances in genetic tools over the past few decades, our ability to accurately assess crop status in the field, at scale, has been severely lacking until recently. Thanks to recent advances in remote sensing and Artificial Intelligence (AI), we can now quantify field scale phenotypic information accurately and integrate the big data into predictive and prescriptive management tools. This review focuses on the use of recent technological advances in remote sensing and AI to improve the resilience of agricultural systems, and we will present a unique opportunity for the development of prescriptive tools needed to address the next decade’s agricultural and human nutrition challenges.

### Conclusion
- El sistema HTP basado en UAS ha demostrado ser una plataforma precisa y fiable para cuantificar la información fenotípica a escala de campo, y también puede integrarse con el GWAS incluso para acelerar los ciclos de mejora en muchos cultivos.

Cita del artículo @JUN


