---
title: "JC: Efecto de la fertilización nitrogenada y fosforada en el rendimiento de papa"
description: |
  El viernes 13 de noviembre de 2020 a horas 16:00, se presentó el artículo original: "Effect of nitrogen and phosphorus fertilization sources on the potato crop yield (*Solanum tuberosum* L.)".
categories:
  - Potato
  - Agronomics Research
  - Crop Yield
author:
  - name: Expositor Javier Mamani
    url: https://example.com/norajones
    affiliation: Universidad Pública de El Alto
date: 11-09-2020
preview: img.png
output:
  distill::distill_article:
    self_contained: false
bibliography: refs.bib
---
<style>
body {
text-align: justify}
</style>

## Resumen
La papa (*Solanum tuberosum* L.) es un cultivo exigente con respecto a las prácticas de fertilización, y su productividad también depende de la variedad utilizada, las condiciones ambientales, la fertilidad del suelo y el manejo del cultivo. El objetivo de este estudio fue investigar el efecto de interacción de las fuentes de fertilización nitrogenadas y fosforadas en el rendimiento del cultivo de papa. Se estableció un diseño factorial 3×3 de bloques al azar con, nueve tratamientos y cuatro repeticiones. La variedad evaluada fue INIA-303 Canchan con tres fuentes de fertilización nitrogenada: nitrato de amonio (NA), sulfato de amonio (SA) y urea, y tres fuentes de fósforo: fosfato monoamónico (FMA), fosfato diamónico (FDM) y superfosfato triple (SFT). Las variables estudiadas fueron rendimiento total, rendimiento comercial, número de tubérculos por planta, peso del tubérculo por planta. La variedad INIA-303 Canchan, mostró respuestas positivas a las combinaciones de fuentes de fertilización de nitrógeno y fósforo bajo las condiciones del suelo y el clima donde se realizó la investigación. En la combinación NA+FDM se encontró el mayor rendimiento total, rendimiento comercial, número y peso de tubérculos por planta (P<0.01). Las mezclas recomendadas para la fertilización de la variedad de papa Canchan INIA-303, para lograr rendimientos entre 32,45 t ha^-1^ a 33,98 t ha^-1^, bajo las condiciones del área de estudio son NA+FDM, SA+FMA y NA+FMA.

## Conclusión del Journal Club
En el título del artículo se usó la palabra "Effect"; sin embargo, en muchas revistas se trata de no dar utilidad a esta palabra.

La metodología en lo que refiere a los tratamientos de la investigación, no menciona muchos detalles para que la investigación sea reproducible.

Los resultados de la investigación no responden de manera clara a los objetivos de la investigación.

Los autores en su conclusión resaltan la variedad; sin embargo, deberían enfatizar los resultados mas sobresalientes en función a los objetivos planteados.


Cita del artículo[@refmanager]
