---
title: "Potasio en el crecimiento de la quinua"
description: |
  El viernes 23 de abril de 2021 a horas 16:00, se discutió el artículo de revisión: "Potassium, an important element to improve water use efficiency and growth parameters in quinoa (Chenopodium quinoa) under saline conditions".
categories:
  - Quinoa
  - Potassium
  - Efficiency
author:
  - name: Veronica Lecona
    url: https://franklinsantos.com
    affiliation: Universidad Pública de El Alto
date: 05-28-2021
preview: qui.jpeg
output:
  distill::distill_article:
    self_contained: false
bibliography: per.bib
---

<style>
body {
text-align: justify}
</style>

### Abstract
Due to changes in the ecosystem and misuse of resources, salinity also increases. Approximately 20% of all irrigated land is affected by salinity and this will increase over time. Therefore, it is necessary to develop more environmentally friendly agricultural techniques but also to exploit potential crops with high nutritional value and tolerance to salinity like quinoa (Chenopodium quinoa Willd.). In this context, potassium is an essential macronutrient for plant growth and development. Furthermore, one of the strategies of some salt-tolerant plants is to increase the uptake of potassium under saline conditions such that the K^+^/Na^+^ ratio is maintained for a proper osmotic regulation in cells. Therefore, a study was conducted to investigate the effect of different concentrations of potassium (0.5, 2 and 6 mM K) on quinoa under different salinities (0, 100 and 200 mM NaCl). According to the results, an adequate supply of potassium under moderate salinity conditions benefited the plant growth, with a higher potassium uptake in the presence of salt. Under saline conditions, plant transpiration decreased significantly with a high correlation with stomatal density and a greater water use efficiency. Therefore, under saline conditions, adequate doses of potassium are highly recommended in quinoa cultivation.

### Conclusion
- A concentraciones de K entre 2 y 6 mM, la producción de biomasa y la WUE aumentaron.
- El WUE también se incrementó en condiciones salinas debido a una disminución de la transpiración de la planta. 
Existe una correlación positiva entre la transpiración y la densidad estomática, por lo que un aumento de la salinidad disminuyó drásticamente la transpiración como consecuencia de una disminución significativa de la densidad estomática. 
- La quinoa es capaz de absorber más K+ bajo condiciones salinas para mantener la relación K^+^/Na^+^ como mecanismo para evitar el estrés salino.
- El K^+^ es importante para reducir los posibles daños causados por la salinidad y al mismo tiempo aumentar la productividad del cultivo. 

Cita del artículo @ht



