---
title: "Git y GitHub en estadística y ciencia de datos"
description: |
  El viernes 28 de mayo de 2021 a horas 16:00, se discutió el artículo de revisión: "Implementing Version Control With Git and GitHub as a Learning Objective in Statistics and Data Science Courses".
categories:
  - Git
  - GitHub
  - Version Control
author:
  - name: Franklin Santos
    url: https://franklinsantos.com
    affiliation: Agritech
date: 05-28-2021
preview: git.png
output:
  distill::distill_article:
    self_contained: false
bibliography: refs.bib
---

<style>
body {
text-align: justify}
</style>

### Abstract
A version control system records changes to a file or set of files over time so that changes can be tracked and specific versions of a file can be recalled later. As such, it is an essential element of a reproducible workflow that deserves due consideration among the learning objectives of statistics courses. This article describes experiences and implementation decisions of four contributing faculty who are teaching different courses at a variety of institutions. Each of these faculty has set version control as a learning objective and successfully integrated one such system (Git) into one or more statistics courses. The various approaches described in the article span different implementation strategies to suit student background, course type, software choices, and assessment practices. By presenting a wide range of approaches to teaching Git, the article aims to serve as a resource for statistics and data science instructors teaching courses at any level within an undergraduate or graduate curriculum.

Cita del artículo @do


