---
title: "JC: Fenología estacional de las principales plagas de quinua."
description: |
  El viernes 08 de enero de 2021 a horas 16:00, se discutió el artículo original: "Seasonal Phenology of the Major Insect Pests of Quinoa (*Chenopodium quinoa* Wild.) and Their Natural Enemies in a Traditional Zone and Two New Production Zones of Peru".
categories:
  - Quinoa
  - Insects Pests
  - Natural Enemies
author:
  - name: Veronica Lecoña
    url: https://franklinsantos.com
    affiliation: Universidad Pública de El Alto
date: 01-06-2021
preview: agri.png
output:
  distill::distill_article:
    self_contained: false
bibliography: refs.bib
---
<style>
body {
text-align: justify}
</style>

## Abstract
Over the last decade, the sown area of quinoa (*Chenopodium quinoa* Willd.) has been increasingly expanding in Peru, and new production fields have emerged, stretching from the Andes to coastal areas. The fields at low altitudes have the potential to produce higher yields than those in the highlands. This study investigated the occurrence of insect pests and the natural enemies of quinoa in a traditional production zone, San Lorenzo (in the Andes), and in two new zones at lower altitudes, La Molina (on the coast) and Majes (in the “Maritime Yunga” ecoregion), by plant sampling and pitfall trapping. Our data indicated that the pest pressure in quinoa was higher at lower elevations than in the highlands. The major insect pest infesting quinoa at high densities in San Lorenzo was *Eurysacca melanocampta*; in La Molina, the major pests were *E. melanocampta*, *Macrosiphum euphorbiae* and *Liriomyza huidobrensis*; and in Majes, *Frankliniella occidentalis* was the most abundant pest. The natural enemy complex played an important role in controlling *M. euphorbiae* and *L. huidobrensis* by preventing pest resurgence. The findings of this study may assist quinoa producers (from the Andes and from regions at lower altitudes) in establishing better farming practices in the framework of integrated pest management.

**Keywords**: quinoa; *Eurysacca melanocampta*; *Macrosiphum euphorbiae*; *Liriomyza huidobrensis*; *Frankliniella occidentalis*; natural enemies; IPM; Peru. 

## Conclusiones del Journal Club

- La investigación presenta un aporte significativo para implementar un manejo integrado de plagas de quinua en distintos ambientes.
- Se destacó información de la incidencia estacional de las principales plagas de insectos y sus enemigos naturales.
- Las evidencias de la investigación  establece que la presión de plagas de quinua es mayor en tierras bajas que en las tierras altas.

Cita correcta del artículo @agri
