---
title: "JC: Adopción de cultivos con tolerancia a factores adversos"
description: |
  El viernes 27 de noviembre de 2020 a horas 16:00, se presentó el artículo de revisión: "A scoping review of adoption of climate-resilient crops by small-scale producers in low- and middle-income countries". 
author:
  - name: Franklin Santos
    url: https://example.com/norajones
date: 11-23-2020
preview: clim.png
output:
  distill::distill_article:
    self_contained: false
bibliography: refs.bib
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Resumen del artículo
Se han recomendado cultivos y variedades de cultivos resistentes al clima como una forma para que los agricultores enfrenten o se adapten al cambio climático, pero a pesar de los aparentes beneficios, las tasas de adopción por parte de los pequeños agricultores son muy variables. Aquí presentamos una revisión de alcance, utilizando PRISMA-P (Elementos de informe preferidos para la revisión sistemática y los protocolos de metaanálisis), que examina las condiciones que han llevado a la adopción de cultivos resistentes al clima durante los últimos 30 años en países de ingresos bajos y medios. El análisis descriptivo realizado en 202 artículos muestra que los pequeños productores adoptaron cultivos y variedades resistentes al clima para hacer frente a tensiones abióticas como la sequía, el calor, las inundaciones y la salinidad. El rasgo más prevalente en nuestro conjunto de datos fue la tolerancia a la sequía, seguido de la eficiencia en el uso del agua. Nuestro análisis encontró que los determinantes más importantes de la adopción de cultivos resilientes al clima fueron la disponibilidad y efectividad de los servicios de extensión y la divulgación, seguidos por los niveles de educación de los jefes de hogar, el acceso de los agricultores a insumos, especialmente semillas y fertilizantes, y la situación socioeconómica de familias de agricultores. Alrededor del 53% de los estudios informaron que las diferencias sociales como el sexo, la edad, el estado civil y la etnia afectaron la adopción de variedades o cultivos como estrategias de adaptación al cambio climático. Sobre la base de la evidencia recopilada, este estudio presenta una serie de vías e intervenciones que podrían contribuir a mayores tasas de adopción de cultivos resistentes al clima y reducir la desaprobación.

### Conclusiones del Journal Club

El artículo fue reflexivo para nuestro contexto de investigación y transferencia de tecnología. De la cual se extrae las siguientes **acciones específicas para aumentar la adopción de cultivos resistentes al clima**.

* Proporcionar programas de extensión.
* Brindar acceso a instrumentos financieros (crédito, seguros y préstamos)
* Implementar programas comunitarios
* Promoción de programas e investigaciones de conservación de germoplasma
* Proporcionar acceso a fertilizantes, plaguicidas y otros insumos
* Sensibilización sobre el cambio climático, el tiempo y los impactos
* Sensibilización sobre cultivos resistentes al clima
* Promover el desarrollo de infraestructura, especialmente riego y caminos.
* Programas específicos para jóvenes y mujeres para involucrarlos en la adopción
* Proporcionar acceso a semillas resistentes al clima
* Proporcionar opciones resistentes al clima de bajo costo para los agricultores
* Iniciativas centradas en la ganadería para abordar el desarrollo de forrajes
* Vincular el apoyo a cultivos resilientes al clima como parte de los esfuerzos de reducción de la pobreza

**Recomendaciones**

* El acceso y la disponibilidad de semillas resistentes al clima deben combinarse con servicios de asesoramiento pertinentes y oportunos, como los sistemas de alerta temprana del clima.
* Garantizar que los agricultores tengan múltiples opciones de acceso a semillas mejoradas. Esto se puede lograr potenciando las redes sociales existentes, como las organizaciones de agricultores.
* Los servicios de extensión debe incluir a varios actores, como grupos de mujeres, universidades, el sector privado y organizaciones no gubernamentales a fin de brindar información personalizada y apropiada para las diversas necesidades.
* Se necesitan estudios de alta calidad sobre cómo los miembros de los hogares, y no solo los jefes de hogar, toman decisiones sobre cómo responder al cambio climático. 
* Las políticas nacionales deben apoyar el acceso de los agricultores a otros activos y servicios, como la educación, la tierra, los servicios financieros y diversas oportunidades de generación de ingresos. 
* Se necesita un enfoque de intervenciones múltiples para promover la adopción de cultivos resistentes al clima.
* Los agricultores no adoptarán cultivos resistentes al clima únicamente sobre la base de cualidades de adaptación ambiental. Los programas de desarrollo y mejoramiento deben considerar las preferencias de los agricultores y los rasgos del mercado.
* Exigir la recopilación de datos desglosados para identificar las estrategias que están funcionando y para quién están trabajando en las encuestas e investigaciones agrícolas permitirá a los responsables de la formulación de políticas y los donantes responder con intervenciones más apropiadas e informadas.

Cita del artículo[@refmanager]


